apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/address-pool: ftps-ip

  labels:
    run: ftps
spec:
  ports:
  - port: 21
    targetPort: 21
    protocol: TCP
    name: ftps21
  - port: 20
    targetPort: 20
    protocol: TCP
    name: ftps20
  - port: 30025
    targetPort: 30025
    protocol: TCP
    name: ftps30025

  selector:
    run: ftps
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      run: ftps
  replicas: 1
  template:
    metadata:
      labels:
        run: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_alpine
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 30025

