apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nginx.yaml
- ftps.yaml
- mysql-deployment.yaml
- wordpress-deployment.yaml
- phpmyadmin.yaml
- telegraf.yaml
- grafana.yaml
- influxdb.yaml
