apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 22
    targetPort: 22
    protocol: TCP
    name: http22

  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-alpine
        imagePullPolicy: Never
        ports:
         - containerPort: 80
         - containerPort: 443
         - containerPort: 22
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'ps aux | egrep [s]shd'   
          initialDelaySeconds: 5  
          periodSeconds: 1
