apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/adress-pool: default
  labels:
    app: phpmyadmin
spec:
  ports:
    - port: 5000
  selector:
    app: phpmyadmin
    tier: frontend
  type: LoadBalancer

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: frontend
    spec:
      containers:
      - image: phpmyadmin_alpine 
        imagePullPolicy: Never
        name: phpmyadmin
        ports:
        - containerPort: 5000
          name: phpmyadmin
        livenessProbe:
          httpGet:
            path: /
            port: 5000
            httpHeaders:
            - name: Custom-Header2
              value: Awesome1
          initialDelaySeconds: 3
          periodSeconds: 3
