FROM alpine:3.11.3

RUN apk update && apk upgrade --available

RUN apk add --no-cache openrc

RUN apk add openssl && apk add vim && apk add nginx

RUN openssl req -x509 -nodes -days 365 -subj "/C=CA/ST=QC/O=Company, Inc./CN=mydomain.com" -addext "subjectAltName=DNS:mydomain.com" -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt;

ADD index.html var/www/localhost/htdocs/

RUN rm etc/nginx/conf.d/default.conf

ADD default.conf etc/nginx/conf.d/

RUN mkdir /run/nginx && touch /run/nginx/nginx.pid

ADD start.sh /start.sh

RUN chmod 755 start.sh

ENTRYPOINT ["sh", "/start.sh"]
