apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - addresses:
      - 172.17.0.40-172.17.0.50
      name: default
      protocol: layer2
    - addresses:
      - 172.17.0.60-172.17.0.60
      name: wordpress-ip
      protocol: layer2
      auto-assign: false
    - addresses:
      - 172.17.0.65-172.17.0.65
      name: ftps-ip
      protocol: layer2
      auto-assign: false
